# Generated by Django 2.1.7 on 2024-12-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0008_address_attitude_bank_education_experience_family_general_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=50, null=True)),
                ('workstartdate', models.DateField(blank=True, null=True)),
                ('booktypename', models.CharField(blank=True, max_length=255, null=True)),
                ('departmentcode', models.CharField(blank=True, max_length=20, null=True)),
                ('departmentname', models.CharField(blank=True, max_length=20, null=True)),
                ('positionname', models.CharField(blank=True, max_length=50, null=True)),
                ('insuredtypename', models.CharField(blank=True, max_length=255, null=True)),
                ('statusname', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
