# Generated by Django 2.1.7 on 2024-12-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0009_subinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subinfo',
            name='workenddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
