# Generated by Django 2.1.7 on 2024-12-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0010_subinfo_workenddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateid', models.CharField(blank=True, max_length=50, null=True)),
                ('addresstypename', models.CharField(blank=True, max_length=255, null=True)),
                ('cityname', models.CharField(blank=True, max_length=100, null=True)),
                ('districtname', models.CharField(blank=True, max_length=100, null=True)),
                ('streetname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateid', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('civilregnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('stateregnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('departmentcode', models.CharField(blank=True, max_length=20, null=True)),
                ('departmentname', models.CharField(blank=True, max_length=20, null=True)),
                ('positioncode', models.CharField(blank=True, max_length=20, null=True)),
                ('positionname', models.CharField(blank=True, max_length=50, null=True)),
                ('phonenumber', models.IntegerField(blank=True, max_length=10, null=True)),
                ('createddate', models.CharField(blank=True, max_length=50, null=True)),
                ('workedtime', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
