# Generated by Django 2.1.7 on 2024-12-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0011_candidateaddress_candidategeneral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidategeneral',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
