# Generated by Django 2.1.7 on 2024-12-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0012_auto_20241209_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidategeneral',
            name='departmentname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
