# Generated by Django 2.1.7 on 2024-12-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0013_auto_20241209_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidategeneral',
            name='positionname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
