# Generated by Django 2.1.7 on 2024-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0014_auto_20241209_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='departmentname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
