# Generated by Django 2.1.7 on 2024-12-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0015_auto_20241209_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_Act_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=20, null=True)),
                ('addresstypename', models.CharField(blank=True, max_length=100, null=True)),
                ('cityname', models.CharField(blank=True, max_length=50, null=True)),
                ('districtname', models.CharField(blank=True, max_length=50, null=True)),
                ('streetname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='in_Act_Attitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=20, null=True)),
                ('punishment', models.CharField(blank=True, max_length=100, null=True)),
                ('punishmentdate', models.DateField(blank=True, null=True)),
                ('punishmenttypeid', models.CharField(blank=True, max_length=100, null=True)),
                ('rewardtypename', models.CharField(blank=True, max_length=100, null=True)),
                ('rewardname', models.CharField(blank=True, max_length=100, null=True)),
                ('rewarddate', models.DateField(blank=True, null=True)),
                ('organizationname', models.CharField(blank=True, max_length=100, null=True)),
                ('rectorshipnumber', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='in_Act_Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=20, null=True)),
                ('bankname', models.CharField(blank=True, max_length=100, null=True)),
                ('bankaccountnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='in_Act_Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=20, null=True)),
                ('edutype', models.CharField(blank=True, max_length=100, null=True)),
                ('edulevel', models.CharField(blank=True, max_length=100, null=True)),
                ('startyearid', models.CharField(blank=True, max_length=4, null=True)),
                ('endyearid', models.CharField(blank=True, max_length=4, null=True)),
                ('countryname', models.CharField(blank=True, max_length=50, null=True)),
                ('cityname', models.CharField(blank=True, max_length=50, null=True)),
                ('schoolname', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='in_Act_Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=20, null=True)),
                ('organizationname', models.CharField(blank=True, max_length=100, null=True)),
                ('departmentname', models.CharField(blank=True, max_length=100, null=True)),
                ('positionname', models.CharField(blank=True, max_length=100, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='in_Act_Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=20, null=True)),
                ('relationshipname', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('workname', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='in_Act_General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('employeecode', models.CharField(blank=True, max_length=10, null=True)),
                ('originname', models.CharField(blank=True, max_length=50, null=True)),
                ('urag', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('stateregnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('employeephone', models.CharField(blank=True, max_length=20, null=True)),
                ('postaddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('educationlevel', models.CharField(blank=True, max_length=50, null=True)),
                ('maritalstatus', models.CharField(blank=True, max_length=50, null=True)),
                ('nooffamilymember', models.IntegerField(blank=True, null=True)),
                ('noofchildren', models.IntegerField(blank=True, null=True)),
                ('departmentname', models.CharField(blank=True, max_length=100, null=True)),
                ('positionname', models.CharField(blank=True, max_length=100, null=True)),
                ('insuredtypename', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='in_Act_Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=20, null=True)),
                ('skillname', models.CharField(blank=True, max_length=100, null=True)),
                ('examname', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='in_Act_SubInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=50, null=True)),
                ('workstartdate', models.DateField(blank=True, null=True)),
                ('workenddate', models.DateField(blank=True, null=True)),
                ('booktypename', models.CharField(blank=True, max_length=255, null=True)),
                ('departmentcode', models.CharField(blank=True, max_length=20, null=True)),
                ('departmentname', models.CharField(blank=True, max_length=20, null=True)),
                ('positionname', models.CharField(blank=True, max_length=50, null=True)),
                ('insuredtypename', models.CharField(blank=True, max_length=255, null=True)),
                ('statusname', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
