# Generated by Django 2.1.7 on 2024-12-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0016_in_act_address_in_act_attitude_in_act_bank_in_act_education_in_act_experience_in_act_family_in_act_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_act_subinfo',
            name='departmentname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
