# Generated by Django 2.1.7 on 2024-12-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0017_auto_20241218_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_act_subinfo',
            name='positionname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
