# Generated by Django 2.1.7 on 2024-12-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0018_auto_20241218_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bankaccountnumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
