# Generated by Django 2.1.7 on 2024-12-31 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0019_auto_20241218_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='in_Act_Address',
            new_name='Address_24',
        ),
        migrations.RenameModel(
            old_name='in_Act_Attitude',
            new_name='Attitude_24',
        ),
        migrations.RenameModel(
            old_name='Bank',
            new_name='Bank_24',
        ),
        migrations.RenameModel(
            old_name='CandidateAddress',
            new_name='CandidateAddress_24',
        ),
        migrations.RenameModel(
            old_name='CandidateGeneral',
            new_name='CandidateGeneral_24',
        ),
        migrations.RenameModel(
            old_name='Education',
            new_name='Education_24',
        ),
        migrations.RenameModel(
            old_name='in_Act_Experience',
            new_name='Experience_24',
        ),
        migrations.RenameModel(
            old_name='in_Act_Family',
            new_name='Family_24',
        ),
        migrations.RenameModel(
            old_name='in_Act_General',
            new_name='General_24',
        ),
        migrations.RenameModel(
            old_name='Address',
            new_name='in_Act_Address_24',
        ),
        migrations.RenameModel(
            old_name='Attitude',
            new_name='in_Act_Attitude_24',
        ),
        migrations.RenameModel(
            old_name='in_Act_Bank',
            new_name='in_Act_Bank_24',
        ),
        migrations.RenameModel(
            old_name='in_Act_Education',
            new_name='in_Act_Education_24',
        ),
        migrations.RenameModel(
            old_name='Experience',
            new_name='in_Act_Experience_24',
        ),
        migrations.RenameModel(
            old_name='Family',
            new_name='in_Act_Family_24',
        ),
        migrations.RenameModel(
            old_name='General',
            new_name='in_Act_General_24',
        ),
        migrations.RenameModel(
            old_name='in_Act_Skills',
            new_name='in_Act_Skills_24',
        ),
        migrations.RenameModel(
            old_name='in_Act_SubInfo',
            new_name='in_Act_SubInfo_24',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skills_24',
        ),
        migrations.RenameModel(
            old_name='SubInfo',
            new_name='SubInfo_24',
        ),
    ]
