# Generated by Django 2.1.7 on 2024-12-31 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0021_address_attitude_bank_candidateaddress_candidategeneral_education_experience_family_general_in_act_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address_24',
        ),
        migrations.DeleteModel(
            name='Attitude_24',
        ),
        migrations.DeleteModel(
            name='Bank_24',
        ),
        migrations.DeleteModel(
            name='CandidateAddress_24',
        ),
        migrations.DeleteModel(
            name='CandidateGeneral_24',
        ),
        migrations.DeleteModel(
            name='Education_24',
        ),
        migrations.DeleteModel(
            name='Experience_24',
        ),
        migrations.DeleteModel(
            name='Family_24',
        ),
        migrations.DeleteModel(
            name='General_24',
        ),
        migrations.DeleteModel(
            name='in_Act_Address_24',
        ),
        migrations.DeleteModel(
            name='in_Act_Attitude_24',
        ),
        migrations.DeleteModel(
            name='in_Act_Bank_24',
        ),
        migrations.DeleteModel(
            name='in_Act_Education_24',
        ),
        migrations.DeleteModel(
            name='in_Act_Experience_24',
        ),
        migrations.DeleteModel(
            name='in_Act_Family_24',
        ),
        migrations.DeleteModel(
            name='in_Act_General_24',
        ),
        migrations.DeleteModel(
            name='in_Act_Skills_24',
        ),
        migrations.DeleteModel(
            name='in_Act_SubInfo_24',
        ),
        migrations.DeleteModel(
            name='Skills_24',
        ),
        migrations.DeleteModel(
            name='SubInfo_24',
        ),
    ]
