# Generated by Django 2.2 on 2025-05-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0024_address_attitude_bank_candidateaddress_candidategeneral_education_experience_family_general_in_act_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='family_24',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='in_act_family',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='in_act_family_24',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
