# Generated by Django 2.2 on 2025-06-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veritech_api', '0025_auto_20250522_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='currentstatusname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='statusname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
