# Generated by Django 2.1.7 on 2025-10-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0013_auto_20240627_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strrent',
            name='rent_mo_fee_annex1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Түрээсийн төлбөр 12'),
        ),
    ]
