# Generated by Django 2.1.7 on 2024-11-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0052_auto_20241111_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconsultant',
            name='store_type',
            field=models.IntegerField(default=0, verbose_name='store type'),
        ),
    ]
