# Generated by Django 2.1.7 on 2024-12-02 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0053_storeconsultant_store_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HisAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('sc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_no', models.CharField(blank=True, max_length=5, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Year')),
                ('month', models.CharField(blank=True, max_length=12, null=True, verbose_name='Month')),
                ('team_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Team No')),
                ('store_cons', models.CharField(blank=True, max_length=50, null=True, verbose_name='Store Consultant')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='Tags and Store IDs')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_consultant.Area')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='his_store_allocations', to='store_consultant.Consultants')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='his_sc_allocations', to='store_consultant.StoreConsultant')),
            ],
            options={
                'verbose_name': 'Historical Allocation',
                'verbose_name_plural': 'Historical Allocations',
                'db_table': 'his_allocation',
            },
        ),
    ]
