# Generated by Django 2.1.7 on 2024-12-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0054_hisallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisallocation',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
