# Generated by Django 2.1.7 on 2024-12-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0055_auto_20241203_1550'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consultants',
            table='sc_mst',
        ),
    ]
