# Generated by Django 2.1.7 on 2024-12-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0056_auto_20241216_1122'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allocation',
            table='team_allocation',
        ),
    ]
