# Generated by Django 2.1.7 on 2024-12-24 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_consultant', '0057_auto_20241216_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Year')),
                ('month', models.CharField(blank=True, max_length=12, null=True, verbose_name='Month')),
                ('team_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Team no')),
                ('store_cons', models.CharField(blank=True, max_length=50, null=True, verbose_name='Store Consultant')),
                ('storeID', models.CharField(blank=True, max_length=5, null=True, verbose_name='Store ID')),
                ('store_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Store name')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='Tags and Store IDs')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_consultant.Area')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_consultant.Consultants')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_temp_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_temp_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Temporary Allocation',
                'db_table': 'team_allocation_temp',
            },
        ),
    ]
