# Generated by Django 2.1.7 on 2024-12-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0058_allocationtemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SC_Store_AllocationTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('sc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_no', models.CharField(blank=True, max_length=5, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_allocations_temp', to='store_consultant.Consultants')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc_allocations_temp', to='store_consultant.StoreConsultant')),
            ],
            options={
                'verbose_name': 'SC Store Allocation',
                'verbose_name_plural': 'SC Store Allocations',
                'db_table': 'sc_store_allocationTemp',
            },
        ),
    ]
