# Generated by Django 2.1.7 on 2024-12-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0059_sc_store_allocationtemp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sc_store_allocationtemp',
            table='sc_store_allocation_temp',
        ),
    ]
