# Generated by Django 2.1.7 on 2025-01-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0060_auto_20241224_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconsultant',
            name='am_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Дэлгүүрийн туслах менежерийн тоо'),
        ),
        migrations.AlterField(
            model_name='storeconsultant',
            name='sm_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Дэлгүүрийн менежерийн тоо'),
        ),
    ]
