# Generated by Django 2.1.7 on 2025-01-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0061_auto_20250102_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconsultant',
            name='ser_Umoney',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Автобусны карт цэнэглэгчтэй эсэх'),
        ),
        migrations.AlterField(
            model_name='storeconsultant',
            name='ser_delivery',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Хүргэлт'),
        ),
        migrations.AlterField(
            model_name='storeconsultant',
            name='ser_lottery',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Сугалаа'),
        ),
        migrations.AlterField(
            model_name='storeconsultant',
            name='ser_pow_bank',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Зөөврийн цэнэглэгч түрээс'),
        ),
        migrations.AlterField(
            model_name='storeconsultant',
            name='ser_print',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Хэвлэл'),
        ),
        migrations.AlterField(
            model_name='storeconsultant',
            name='ser_storabox',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Stora Box'),
        ),
        migrations.AlterField(
            model_name='storeconsultant',
            name='ser_ticket',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Тасалбар'),
        ),
        migrations.AlterField(
            model_name='storeconsultant',
            name='squat_toilet_yn',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Дэлгүүрийн гадна модон 00 той эсэх'),
        ),
        migrations.AlterField(
            model_name='storeconsultant',
            name='tv_screen',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tv screen'),
        ),
        migrations.AlterField(
            model_name='storeconsultant',
            name='up_frz_ice',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Horizontal icemark freezer'),
        ),
    ]
