# Generated by Django 2.1.7 on 2025-01-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0062_auto_20250102_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconsultant',
            name='sub_rent2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дамжуулдаг түрээсэлдэг төрөл2'),
        ),
    ]
