# Generated by Django 2.1.7 on 2025-01-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0063_auto_20250114_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_store_allocationtemp',
            name='team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
