# Generated by Django 2.1.7 on 2025-01-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0064_sc_store_allocationtemp_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_store_allocationtemp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
