# Generated by Django 2.1.7 on 2025-01-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0065_sc_store_allocationtemp_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sc_store_allocationtemp',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sc_store_allocationtemp',
            name='team_id',
        ),
    ]
