# Generated by Django 2.1.7 on 2025-03-11 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0066_auto_20250127_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='SC_Store_AllocationTemp_Deleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('sc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_no', models.CharField(blank=True, max_length=5, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_store_allocations_temp', to='store_consultant.Consultants')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_sc_allocations_temp', to='store_consultant.StoreConsultant')),
            ],
            options={
                'verbose_name': 'SC Store Allocation Deleted',
                'verbose_name_plural': 'SC Store Allocations Deleted',
                'db_table': 'sc_store_allocation_temp_deleted',
            },
        ),
    ]
