# Generated by Django 2.1.7 on 2025-03-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0067_sc_store_allocationtemp_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sc_store_allocationtemp_deleted',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='sc_store_allocationtemp_deleted',
            name='store',
        ),
        migrations.DeleteModel(
            name='SC_Store_AllocationTemp_Deleted',
        ),
    ]
