# Generated by Django 2.1.7 on 2025-03-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0068_auto_20250311_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconsultant',
            name='store_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Store email'),
        ),
    ]
