# Generated by Django 2.1.7 on 2025-04-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0069_storeconsultant_store_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconsultant',
            name='use_yn',
            field=models.BooleanField(blank=True, default=1, null=True, verbose_name='Use yn'),
        ),
    ]
