# Generated by Django 2.1.7 on 2025-04-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0070_auto_20250402_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Area active'),
        ),
    ]
