# Generated by Django 2.2 on 2025-04-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0072_consultants_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultants',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='SC active'),
        ),
    ]
