# Generated by Django 2.2 on 2025-04-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0073_auto_20250415_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconsultant',
            name='ost_dt',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Date'),
        ),
    ]
