# Generated by Django 2.2 on 2025-05-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0074_storeconsultant_ost_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
