# Generated by Django 2.2 on 2025-06-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0075_pushstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconsultant',
            name='is_locked',
            field=models.BooleanField(default=False, null=True, verbose_name='Is Locked'),
        ),
    ]
