# Generated by Django 2.2 on 2025-06-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0076_storeconsultant_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconsultant',
            name='store_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Store code'),
        ),
    ]
