# Generated by Django 2.2 on 2025-06-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0077_storeconsultant_store_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeconsultant',
            old_name='store_code',
            new_name='sc_code',
        ),
    ]
