# Generated by Django 2.2 on 2025-06-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0078_auto_20250616_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeconsultant',
            name='sc_code',
        ),
        migrations.AddField(
            model_name='consultants',
            name='sc_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Store code'),
        ),
    ]
