# Generated by Django 2.2 on 2025-06-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0079_auto_20250616_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconsultant',
            name='cls_dt',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Close Date'),
        ),
    ]
