# Generated by Django 2.2 on 2025-06-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_consultant', '0080_storeconsultant_cls_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeconsultant',
            old_name='is_locked',
            new_name='is_locked_sc',
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='is_locked_sp',
            field=models.BooleanField(default=False, null=True, verbose_name='Is Locked'),
        ),
        migrations.AddField(
            model_name='storeconsultant',
            name='is_locked_st',
            field=models.BooleanField(default=False, null=True, verbose_name='Is Locked'),
        ),
    ]
