# Generated by Django 2.1.7 on 2024-12-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0064_storeplanning_address_simple'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='storeEmail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Store email'),
        ),
    ]
