# Generated by Django 2.1.7 on 2024-12-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0065_point_storeemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='storeEmail',
        ),
    ]
