# Generated by Django 2.1.7 on 2025-02-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0067_storeplanning_storeemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(db_index=True, max_length=10)),
                ('store_name', models.CharField(max_length=255)),
                ('nearby_store_id', models.CharField(max_length=10)),
                ('nearby_store_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='nearbystore',
            unique_together={('store_id', 'nearby_store_id')},
        ),
    ]
