# Generated by Django 2.1.7 on 2025-02-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0068_auto_20250219_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbystore',
            name='cluster',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nearbystore',
            name='nearby_cluster',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
