# Generated by Django 2.1.7 on 2025-02-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0069_auto_20250219_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeplanning',
            name='point',
        ),
    ]
