# Generated by Django 2.1.7 on 2025-02-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0070_remove_storeplanning_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeplanning',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_plannings', to='point.Point'),
        ),
    ]
