# Generated by Django 2.1.7 on 2025-03-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0071_storeplanning_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeplanning',
            name='floor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Floor number'),
        ),
    ]
