# Generated by Django 2.1.7 on 2025-03-04 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0072_auto_20250304_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='store_id',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Store ID must be exactly 5 digits (numbers only).')], verbose_name='Store ID'),
        ),
    ]
