# Generated by Django 2.1.7 on 2025-03-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0073_auto_20250304_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbystore',
            name='nearby_store_distance_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance to nearby store (m)'),
        ),
    ]
