# Generated by Django 2.2 on 2025-04-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0074_nearbystore_nearby_store_distance_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbystore',
            name='within_1000m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nearbystore',
            name='within_500m',
            field=models.BooleanField(default=False),
        ),
    ]
