# Generated by Django 2.2 on 2025-04-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0075_auto_20250417_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nearbystore',
            name='within_1000m',
        ),
        migrations.RemoveField(
            model_name='nearbystore',
            name='within_500m',
        ),
    ]
