# Generated by Django 2.2 on 2025-04-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0076_auto_20250417_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbystore',
            name='distance_1000m',
            field=models.FloatField(blank=True, null=True, verbose_name='1000 Distance to nearby store (m)'),
        ),
        migrations.AddField(
            model_name='nearbystore',
            name='distance_500m',
            field=models.FloatField(blank=True, null=True, verbose_name='500 Distance to nearby store (m)'),
        ),
    ]
