# Generated by Django 2.2 on 2025-05-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0077_auto_20250417_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbystore',
            name='addr3_khr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Khoroo'),
        ),
        migrations.AddField(
            model_name='nearbystore',
            name='address_det',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address detail'),
        ),
        migrations.AddField(
            model_name='nearbystore',
            name='address_simple',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address simple'),
        ),
        migrations.AddField(
            model_name='nearbystore',
            name='dist_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='District name'),
        ),
        migrations.AddField(
            model_name='nearbystore',
            name='prov_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Province (City) name'),
        ),
    ]
