# Generated by Django 2.2 on 2025-05-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0078_auto_20250506_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbystore',
            name='ub_center_distance_m',
            field=models.FloatField(blank=True, null=True, verbose_name='UB center distance (m)'),
        ),
    ]
