# Generated by Django 2.2 on 2025-05-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0079_nearbystore_ub_center_distance_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbystore',
            name='origin_ub_distance_m',
            field=models.FloatField(blank=True, null=True, verbose_name='UB center distance of origin store (m)'),
        ),
    ]
