# Generated by Django 2.2 on 2025-05-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0080_nearbystore_origin_ub_distance_m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nearbystore',
            old_name='ub_center_distance_m',
            new_name='nearby_store_ub_center_distance_m',
        ),
        migrations.RenameField(
            model_name='nearbystore',
            old_name='origin_ub_distance_m',
            new_name='store_ub_center_distance_m',
        ),
    ]
