# Generated by Django 2.2 on 2025-05-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0082_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='codename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
