# Generated by Django 2.2 on 2025-07-17 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0083_auto_20250527_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('session_duration', models.DurationField(blank=True, null=True)),
                ('action', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('used_window', models.CharField(max_length=255)),
            ],
        ),
    ]
