# Generated by Django 2.2 on 2025-06-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_trainer', '0005_auto_20240327_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetrainer',
            name='is_locked_st',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
