# Generated by Django 2.1.7 on 2025-03-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='zips/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=20)),
                ('download_count', models.IntegerField(default=0)),
                ('is_download', models.BooleanField(default=False)),
            ],
        ),
    ]
