# Generated by Django 2.1.7 on 2025-03-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zipmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('zip_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zipmanager.ZipFile')),
            ],
        ),
    ]
