# Generated by Django 2.1.7 on 2025-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipmanager', '0002_downloadeddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadeddevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadeddevice',
            name='os_info',
            field=models.CharField(default='Unknown OS', max_length=255),
        ),
        migrations.AlterField(
            model_name='downloadeddevice',
            name='device_name',
            field=models.CharField(default='Unknown Device', max_length=255),
        ),
    ]
