# Generated by Django 2.1.7 on 2025-03-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipmanager', '0003_auto_20250307_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadeddevice',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
