# Generated by Django 2.1.7 on 2025-10-03 15:43

import cupp.license.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0032_auto_20241016_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='lic_file',
            field=models.FileField(blank=True, null=True, upload_to=cupp.license.models.upload_file, verbose_name='License PDF file'),
        ),
    ]
