# Generated by Django 2.1.7 on 2025-11-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0033_maintable_lic_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhistleBlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harm_type', models.CharField(max_length=100)),
                ('damage_causer', models.CharField(blank=True, max_length=200, null=True)),
                ('damage_photo', models.ImageField(blank=True, null=True, upload_to='damage_photos/')),
                ('blower_firstName', models.CharField(max_length=50)),
                ('blower_lastName', models.CharField(max_length=50)),
                ('blower_company', models.CharField(blank=True, max_length=100, null=True)),
                ('blower_position', models.CharField(blank=True, max_length=100, null=True)),
                ('blower_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('blower_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('blower_secret', models.BooleanField(default=False)),
                ('blower_messenger', models.CharField(blank=True, max_length=50, null=True)),
                ('blower_messenger_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Whistle Blow',
                'verbose_name_plural': 'Whistle Blows',
            },
        ),
    ]
