# Generated by Django 2.1.7 on 2025-11-10 09:09

import cupp.license.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0034_whistleblow'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistleblow',
            name='damage_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='whistleblow',
            name='damage_photo',
            field=models.FileField(blank=True, null=True, upload_to=cupp.license.models.upload_file, verbose_name='License PDF file'),
        ),
    ]
