# Generated by Django 2.2 on 2025-06-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfoRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('responseData', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
