# Generated by Django 2.2 on 2025-06-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinforaw',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=10),
        ),
    ]
