# Generated by Django 2.2 on 2025-06-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_api', '0002_auto_20250610_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinforaw',
            name='status',
            field=models.CharField(blank=True, default='PENDING', max_length=10),
        ),
    ]
