# Generated by Django 2.2 on 2025-06-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_api', '0004_emppersonalinforaw'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinforaw',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
