# Generated by Django 2.2 on 2025-07-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_api', '0005_personalinforaw_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinforaw',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
