# Generated by Django 2.2 on 2025-07-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_api', '0006_auto_20250703_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinforaw',
            name='new_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinforaw',
            name='old_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinforaw',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
